OJ-2232 : created new unhappy test for a deceased user
govuk-one-login/ipv-cri-check-hmrc-api pull request #118
Opened 2024-01-17 09:34 UTC by liamStockwellGDS

OJ-2232 : created new unhappy test for a deceased user

## Proposed changes

### What changed

### Why did it change

### Issue tracking

- [OJ-XXXX](https://govukverify.atlassian.net/browse/OJ-XXXX)

## Checklists

### Environment variables or secrets

- [ ] No environment variables or secrets were added or changed

- [ ] Documented in the [README](./blob/main/README.md)
- [ ] Added to deployment repository
- [ ] Added to local startup repository

### Other considerations

- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2024-01-29 11:36 UTC, surajkumar submitted a review, later dismissed

2024-01-29 11:57 UTC, CharlesIC commented on integration-tests/tests/aws/nino-check/nino-check-unhappy.test.ts
> +  it("should fail when user is deceased is invalid", async () => {
```suggestion
  it("should fail when user is deceased", async () => {
```
Bad copy/paste?

2024-01-30 13:10 UTC, CharlesIC requested changes
This branch needs to be rebased on main to get rid of the `Merge branch 'main'` commit, as we don’t want to merge merge commits back into main

2024-01-31 09:49 UTC, CharlesIC approved these changes
Thank you 🙇

2024-01-31 09:54 UTC, merged